db = {
  dalmatien = {
    use = {
      [1] = "chien de compagnie",
    },
    height = "de taille moyenne",
    weight = 32,
    measure = 61,
    origin = "dalmatie",
  },
  ["labrador retriever"] = {
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de rapport",
      [3] = "chien de travail",
      [4] = "chien guide",
      [5] = "chien de chasse",
      [6] = "chien de recherche",
      [7] = "chien d ' assistance",
      [8] = "chien de sauvetage",
      [9] = "chien de détection",
      [10] = "chien policier",
      [11] = "chien truffier",
      [12] = "chien d ' éveil",
    },
    height = "de taille moyenne",
    weight = 0,
    measure = 57,
    origin = "royaume - uni",
  },
  ["spitz allemand"] = {
    use = {
      [1] = "chien de compagnie",
    },
    height = "en cinq variétés de taille",
    weight = 0,
    measure = 49,
    origin = "allemagne",
  },
  beagle = {
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de détection",
      [3] = "chien de chasse",
      [4] = "chien de travail",
      [5] = "chien de garde",
      [6] = "chien de laboratoire",
    },
    height = "de taille petite à moyenne",
    weight = 17,
    measure = 41,
    origin = "angleterre",
  },
  ["samoyède"] = {
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de garde",
    },
    height = "de taille moyenne",
    weight = 0,
    measure = 57,
    origin = "russie européenne",
  },
  ["chien de berger islandais"] = {
    use = {
      [1] = "chien de compagnie",
    },
    height = "de taille inconnue",
    weight = 18,
    measure = 46,
    origin = "islande",
  },
  ["dogue de bordeaux"] = {
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de garde",
    },
    height = "de taille inconnue",
    weight = 80,
    measure = 68,
    origin = "française",
  },
  akita = {
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de garde",
      [3] = "chien policier",
    },
    height = "de grande taille",
    weight = 40,
    measure = 70,
    origin = "japon",
  },
  ["bichon maltais"] = {
    use = {
      [1] = "chien de compagnie",
    },
    origin = "inconnue",
    weight = 4,
    measure = 25,
    height = "de petite taille",
  },
  ["terrier ecossais"] = {
    use = {
      [1] = "chien de compagnie",
    },
    height = "de taille inconnue",
    weight = 10,
    measure = 28,
    origin = "ecosse",
  },
  ["lapphund suedois"] = {
    use = {
      [1] = "chien de compagnie",
    },
    height = "de taille moyenne",
    weight = 0,
    measure = 48,
    origin = "suède",
  },
  ["epagneul breton"] = {
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de rapport",
    },
    height = "de petite taille",
    weight = 0,
    measure = 51,
    origin = "bretagne",
  },
  ["levrier afghan"] = {
    use = {
      [1] = "chien de compagnie",
    },
    height = "de taille inconnue",
    weight = 28,
    measure = 74,
    origin = "afghanistan",
  },
  ["chow-chow"] = {
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de chasse",
      [3] = "chien de garde",
    },
    height = "de taille moyenne",
    weight = 35,
    measure = 56,
    origin = "mongolie",
  },
  ["terre-neuve"] = {
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de chasse",
      [3] = "chien de sauvetage",
    },
    height = "à forte taille",
    weight = 65,
    measure = 71,
    origin = "île canadienne de terre - neuve",
  },
  ["berger allemand"] = {
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de garde",
      [3] = "chien de travail",
      [4] = "guide d ' aveugle",
      [5] = "chien policier",
    },
    height = "de taille moyenne",
    weight = 40,
    measure = 65,
    origin = "allemagne",
  },
  bouledogue = {
    use = {
      [1] = "chien de compagnie",
    },
    origin = "inconnue",
    weight = 11,
    measure = 30,
    height = "de taille moyenne",
  },
  ["golden retriever"] = {
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de rapport",
      [3] = "chien d ' assistance",
      [4] = "chien d ' éveil",
      [5] = "chien guide",
      [6] = "chien de recherche",
      [7] = "chien de sauvetage",
    },
    height = "de taille moyenne",
    weight = 0,
    measure = 61,
    origin = "britannique",
  },
}