db = {
  ["lapphund suedois"] = {
    weight = 0,
    origin = "suède",
    height = "de taille moyenne",
    use = {
      [1] = "chien de compagnie",
    },
    measure = 48,
  },
  ["boarder collie"] = {
    weight = 25,
    origin = "génétique",
    height = "de taille inconnue",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de travail",
    },
    measure = 55,
  },
  ["dogue de bordeaux"] = {
    weight = 80,
    origin = "française",
    height = "de taille inconnue",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de garde",
    },
    measure = 68,
  },
  chihuahua = {
    weight = 3,
    origin = "état de chihuahua",
    height = "sa petite taille",
    use = {
      [1] = "chien de compagnie",
    },
    measure = 16,
  },
  ["terrier ecossais"] = {
    weight = 10,
    origin = "ecosse",
    height = "de taille inconnue",
    use = {
      [1] = "chien de compagnie",
    },
    measure = 28,
  },
  leonberg = {
    weight = 60,
    origin = "inconnue",
    height = "fort grande taille",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de sauvetage",
    },
    measure = 75,
  },
  ["terre-neuve"] = {
    weight = 65,
    origin = "île canadienne de terre - neuve",
    height = "à forte taille",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de chasse",
      [3] = "chien de sauvetage",
    },
    measure = 71,
  },
  ["berger australien"] = {
    weight = 7,
    origin = "australie",
    height = "de taille inconnue",
    use = {
      [1] = "chien de compagnie",
    },
    measure = 58,
  },
  ["basset hound"] = {
    weight = 0,
    origin = "inconnue",
    height = "de petite taille",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de chasse",
      [3] = "chien de travail",
    },
    measure = 38,
  },
  akita = {
    weight = 40,
    origin = "japon",
    height = "de grande taille",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de garde",
      [3] = "chien policier",
    },
    measure = 70,
  },
  ["chow-chow"] = {
    weight = 35,
    origin = "mongolie",
    height = "de taille moyenne",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de chasse",
      [3] = "chien de garde",
    },
    measure = 56,
  },
  ["bichon maltais"] = {
    weight = 4,
    origin = "inconnue",
    height = "de petite taille",
    use = {
      [1] = "chien de compagnie",
    },
    measure = 25,
  },
  ["levrier afghan"] = {
    weight = 28,
    origin = "afghanistan",
    height = "de taille inconnue",
    use = {
      [1] = "chien de compagnie",
    },
    measure = 74,
  },
  ["samoyède"] = {
    weight = 0,
    origin = "russie européenne",
    height = "de taille moyenne",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de garde",
    },
    measure = 57,
  },
  beagle = {
    weight = 17,
    origin = "angleterre",
    height = "de taille petite à moyenne",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de détection",
      [3] = "chien de chasse",
      [4] = "chien de travail",
      [5] = "chien de garde",
      [6] = "chien de laboratoire",
    },
    measure = 41,
  },
  ["epagneul breton"] = {
    weight = 0,
    origin = "bretagne",
    height = "de petite taille",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de rapport",
    },
    measure = 51,
  },
  ["chien de berger islandais"] = {
    weight = 18,
    origin = "islande",
    height = "de taille inconnue",
    use = {
      [1] = "chien de compagnie",
    },
    measure = 46,
  },
  ["golden retriever"] = {
    weight = 0,
    origin = "britannique",
    height = "de taille moyenne",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de rapport",
      [3] = "chien d ' assistance",
      [4] = "chien d ' éveil",
      [5] = "chien guide",
      [6] = "chien de recherche",
      [7] = "chien de sauvetage",
    },
    measure = 61,
  },
  ["labrador retriever"] = {
    weight = 0,
    origin = "royaume - uni",
    height = "de taille moyenne",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de rapport",
      [3] = "chien de travail",
      [4] = "chien guide",
      [5] = "chien de chasse",
      [6] = "chien de recherche",
      [7] = "chien d ' assistance",
      [8] = "chien de sauvetage",
      [9] = "chien de détection",
      [10] = "chien policier",
      [11] = "chien truffier",
      [12] = "chien d ' éveil",
    },
    measure = 57,
  },
  ["shih tzu"] = {
    weight = 0,
    origin = "inconnue",
    height = "de taille inconnue",
    use = {
      [1] = "chien de compagnie",
    },
    measure = 0,
  },
  dalmatien = {
    weight = 32,
    origin = "dalmatie",
    height = "de taille moyenne",
    use = {
      [1] = "chien de compagnie",
    },
    measure = 61,
  },
  ["berger allemand"] = {
    weight = 40,
    origin = "allemagne",
    height = "de taille moyenne",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de garde",
      [3] = "chien de travail",
      [4] = "guide d ' aveugle",
      [5] = "chien policier",
    },
    measure = 65,
  },
  ["spitz allemand"] = {
    weight = 0,
    origin = "allemagne",
    height = "en cinq variétés de taille",
    use = {
      [1] = "chien de compagnie",
    },
    measure = 49,
  },
  colley = {
    weight = 30,
    origin = "britannique",
    height = "de taille inconnue",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de chasse",
    },
    measure = 61,
  },
  boxer = {
    weight = 35,
    origin = "allemande",
    height = "de taille moyenne",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de travail",
    },
    measure = 63,
  },
  ["irish wolfhound"] = {
    weight = 94,
    origin = "inconnue",
    height = "de grande taille",
    use = {
      [1] = "chien de compagnie",
      [2] = "chien de garde",
      [3] = "chien de chasse",
    },
    measure = 86,
  },
  bouledogue = {
    weight = 11,
    origin = "inconnue",
    height = "de taille moyenne",
    use = {
      [1] = "chien de compagnie",
    },
    measure = 30,
  },
}